name: netvetta
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.2.4
  http: ^1.1.0
  get_secure_storage: ^1.0.4
  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.1.14
  connectivity_plus: ^4.0.2
  flutter_local_notifications: ^15.1.1
  workmanager: ^0.5.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
